### YamlMime:Role 
title: DevOps Engineer 
metadata: 
  title: DevOps Engineer 
  description: DevOps Engineer 将人员、流程和技术结合起来，不断提供可满足最终用户需求和业务目标的有价值的产品和服务。
uid: role.devops-engineer 
summary: | 
  DevOps Engineer 将人员、流程和技术结合起来，不断提供可满足最终用户需求和业务目标的有价值的产品和服务。
subTitle: DevOps Engineer 将人员、流程和技术结合起来，不断提供可满足最终用户需求和业务目标的有价值的产品和服务。
certificationPaths: 
- title: DevOps Engineer
  linkedInKeywords: DevOps Engineer
  uid: certification-path.devops-engineer
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.azure-administrator
    levels:
    - intermediate
  - uid: certification.azure-developer
    levels:
    - intermediate
  - uid: certification.devops-engineer
    levels:
    - advanced    
certifications:
- uid: certification.devops-engineer
  requiredExams:
  - uid: exam.az-400
resources:
- title: Microsoft培训和认证指南
  description: 通过简明的培训和认证指南探索所有认证。
  href: https://aka.ms/TrainingCertDeck
- title: 培训和认证海报
  description: 通过此培训和认证海报选择成功的道路。
  href: https://aka.ms/traincertposter
- title: 认证支持
  href: ../help.md
  description: 通过Microsoft认证支持论坛获取帮助。论坛主持人将在一个工作日后回应，周一至周五。
